server:
  port: 8081
  servlet:
    context-path: /

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

sendgrid:
  api-key:
  from-email:



logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
